(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["SEDM3`Timesaving`",{"ErrorBarPlots`"}];


makeFittable::usage="";
makePlotable::usage="";
makeWeights::usage= "";




Begin["`Private`"];

makeFittable={#[[1]],#[[2,1]]}&;
makePlotable={{#[[1]],#[[2,1]]},ErrorBar[#[[2,2]]]}&;
makeWeights=Module[{\[CapitalDelta]ys},
\[CapitalDelta]ys=#[[2,2]];
1/\[CapitalDelta]ys^2]
ernd[pt_,dp_:2]:=Module[{me},
me=MantissaExponent[pt[[2]]];
(1.0{Round[pt[[1]],10^(-dp+#[[2]])],Round[#[[1]],10^-dp]*10^#[[2]]}&/@{me})[[1]]]


End[];
EndPackage[];
