(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["SEDM4`Utilities`"];


(* ::Input::Initialization:: *)
getClusterFiles::usage="Returns a list of files that belong to the named cluster. It expects the files to be stored in the standard structure. It doesn't query the database - it really looks for files on your hard disk.";
getBlockFile::usage="Give it a cluster and cluster index and it'll return the filename for the block. It will only return a value if you have that block in your data root.";
standardErrorOfSampleMean::usage="Puts the function that they inexplicably removed from 5.2 back in. Calculates the s.d. over sqrt the number of samples.";
weightedMean::usage="Takes  a list of {value, error} pairs and calculates the weighted mean.";
timeStampToDateList::usage="";


(* ::Input::Initialization:: *)



(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
kDataVersionString="v4";


(* ::Input::Initialization:: *)
sedm4::noBlockFile="There is no file corresponding to that block on disk.";


(* ::Input::Initialization:: *)
getClusterFiles[clusterName_]:=FileNames[getDirectoryFromBrokenName[breakUpClusterName[#]]<>"\\"<>#<>"*.zip"]&[clusterName]


(* ::Input::Initialization:: *)
getBlockFile[clusterName_,clusterIndex_]:=Module[{files},
files=FileNames[getDirectoryFromBrokenName[breakUpClusterName[#]]<>"\\"<>#<>"_"<>ToString[clusterIndex]<>".zip"]&[clusterName];
If[Length[files] != 1
,
Message[sedm4::noBlockFile];
Abort[];
,
files[[1]]
]
]


(* ::Input::Initialization:: *)
breakUpClusterName[cluster_]:=StringCases[cluster,RegularExpression["(\\d\\d)(\\w+)(\\d\\d)(\\d\\d)"]:>{"$1","$2","$3","$4"}][[1]];

monthReps={
"Jan"->"January",
"Feb"->"February",
"Mar"->"March",
"Apr"->"April",
"May"->"May",
"Jun"->"June",
"Jul"->"July",
"Aug"->"August",
"Sep"->"September",
"Oct"->"October",
"Nov"->"November",
"Dec"->"December"
};

getDirectoryFromBrokenName[brokenName_]:=Module[{yearString},
yearString="20" <>brokenName[[3]];
Global`$dataRoot<>"\\sedm\\"<>kDataVersionString<>"\\" <>yearString<>"\\"<>(brokenName[[2]]/.monthReps)<>yearString
];

standardErrorOfSampleMean[data_]:=StandardDeviation[data]/Sqrt[Length[data]]

timeStampToDateList[ts_]:=DateList[ts/10^7+AbsoluteTime[{1,1,1,0,0,0}]//N]


(* ::Input::Initialization:: *)
weightedMean[chanList_]:=Module[{wvr,wedm,wse},
wvr=(1/Plus@@ (1/#[[2]]^2&/@ chanList));
wedm =wvr(Plus@@((#[[1]]/#[[2]]^2)&/@chanList));
wse = Sqrt[wvr];
{wedm,wse}
];


(* ::Input::Initialization:: *)
End[];
EndPackage[];
