(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)

BeginPackage["FittingTools`","Graphics`Colors`","Statistics`NonlinearFit`","Statistics`Common`RegressionCommon`",
  "Statistics`DataManipulation`"]







lorentz::usage="lorentz[y0_,a_,xc_,w_,x_] is a model Lorentzian, with offset y0, amplitude a, centroid xc and FWHM w"

gaussian::usage="gaussian[y0,a,xc,w,x] is a model Gaussian"
lorentzFit::usage="lorentzFit[data] fits a model Lorentzian to the data"
gaussFit::usage="gaussFit[data] fits a model Gaussian to the data"
lorentzFitManual::usage="lorentzFitManual[data,offsetGuess,ampGuess,centroidGuess,widthGuess] fits a lorentzian to the data using the inital guesses specified by the parameters"

getFitResult::usage="getFitResult[] returns the result of the fit"
getFitGraph::usage="getFitGraph[] retuns a graph showing the fit"
getGuesses::usage="getGuesses[] returns the initial guesses made by the algorithm for the fit parameters"

getBase::usage="getBase[] Returns the value of the baseline produced by the fit"

getAmplitude::usage="getAmplitude[] returns the value of the amplitude produced by the fit"

getCentroid::usage="getCentroid[] returns the value of the centroid produced by the fit"

getWidth::usage="getWidth[] returns the value of the FWHM produced by the fit"



Begin["`Private`"]

\!\(lorentz[y0_, a_, xc_, w_, x_] := y0 + a*\((w\^2/4)\)/\((\((x - xc)\)\^2 + \((w\^2/4)\))\)\[IndentingNewLine]
  gaussian[y0_, a_, xc_, w_, x_] := y0 + a*Exp[\(-4\) Log[2] \((x - xc)\)\^2/w\^2]\)



lorentzFit[
    data_]:=(maxPos=
      data\[LeftDoubleBracket]Position[data,
            Max[data\[LeftDoubleBracket]All,
                2\[RightDoubleBracket]]]\[LeftDoubleBracket]1,
          1\[RightDoubleBracket]\[RightDoubleBracket];
minPos=data\[LeftDoubleBracket]
        Position[data,
            Min[data\[LeftDoubleBracket]All,
                2\[RightDoubleBracket]]]\[LeftDoubleBracket]1,
          1\[RightDoubleBracket]\[RightDoubleBracket];
amp=maxPos\[LeftDoubleBracket]2\[RightDoubleBracket]-
        minPos\[LeftDoubleBracket]2\[RightDoubleBracket];
binned=BinCounts[
        data\[LeftDoubleBracket]All,
          2\[RightDoubleBracket],{minPos\[LeftDoubleBracket]2\
\[RightDoubleBracket],maxPos\[LeftDoubleBracket]2\[RightDoubleBracket],
          amp/10}];
centre=If[
        Position[binned,Max[binned]]\[LeftDoubleBracket]1,
            1\[RightDoubleBracket]\[GreaterEqual] 5,minPos,maxPos];
base=If[Position[binned,Max[binned]]\[LeftDoubleBracket]1,
              1\[RightDoubleBracket]\[GreaterEqual] 5,maxPos,
          minPos]\[LeftDoubleBracket]2\[RightDoubleBracket];
amp=centre\[LeftDoubleBracket]2\[RightDoubleBracket]-base;
    For[tot=0;i=2,
      i\[LessEqual]  
        Length[data\[LeftDoubleBracket]All,2\[RightDoubleBracket]],i++, 
      tot+=(data\[LeftDoubleBracket]i,2\[RightDoubleBracket]-
              base)*(data\[LeftDoubleBracket]i,1\[RightDoubleBracket]-
              data\[LeftDoubleBracket]i-1,1\[RightDoubleBracket])];
    width=Abs[tot/amp];
    fitResult=
      NonlinearRegress[data,lorentz[baseFit,ampFit,centroidFit,widthFit,x],
        x,{{baseFit,base},{ampFit,amp},{centroidFit,
            centre\[LeftDoubleBracket]1\[RightDoubleBracket]},{widthFit,
            width}},RegressionReport\[Rule]{BestFitParameters,ParameterTable},
        MaxIterations\[Rule]150];
    fitGraph=
      Show[{Plot[
            lorentz[baseFit,ampFit,centroidFit,widthFit,
                x]/.(BestFitParameters/.fitResult),{x,First[First[data]],
              First[Last[data]]},PlotStyle\[Rule]Red,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity],
          ListPlot[data,PlotJoined\[Rule]False,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity]},
        DisplayFunction\[Rule]$DisplayFunction];
    getFitResult[] = fitResult;
    getFitGraph[] = fitGraph;
    getGuesses[]={base,amp,centre,width};
    getBase[]=baseFit/.(BestFitParameters/.fitResult);
    getAmplitude[]=ampFit/.(BestFitParameters/.fitResult);
    getCentroid[]=centroidFit/.(BestFitParameters/.fitResult);
    getWidth[]=widthFit/.(BestFitParameters/.fitResult);)

gaussFit[data_]:=(maxPos=
      data\[LeftDoubleBracket]Position[data,
            Max[data\[LeftDoubleBracket]All,
                2\[RightDoubleBracket]]]\[LeftDoubleBracket]1,
          1\[RightDoubleBracket]\[RightDoubleBracket];
    minPos=
      data\[LeftDoubleBracket]Position[data,
            Min[data\[LeftDoubleBracket]All,
                2\[RightDoubleBracket]]]\[LeftDoubleBracket]1,
          1\[RightDoubleBracket]\[RightDoubleBracket];
    amp=maxPos\[LeftDoubleBracket]2\[RightDoubleBracket]-
        minPos\[LeftDoubleBracket]2\[RightDoubleBracket];
    binned=
      BinCounts[
        data\[LeftDoubleBracket]All,
          2\[RightDoubleBracket],{minPos\[LeftDoubleBracket]2\
\[RightDoubleBracket],maxPos\[LeftDoubleBracket]2\[RightDoubleBracket],
          amp/10}];
    centre=
      If[Position[binned,Max[binned]]\[LeftDoubleBracket]1,
            1\[RightDoubleBracket]\[GreaterEqual] 5,minPos,maxPos];
    base=If[
          Position[binned,Max[binned]]\[LeftDoubleBracket]1,
              1\[RightDoubleBracket]\[GreaterEqual] 5,maxPos,
          minPos]\[LeftDoubleBracket]2\[RightDoubleBracket];
    amp=centre\[LeftDoubleBracket]2\[RightDoubleBracket]-base;
    For[tot=0;i=2,
      i\[LessEqual]  
        Length[data\[LeftDoubleBracket]All,2\[RightDoubleBracket]],i++, 
      tot+=(data\[LeftDoubleBracket]i,2\[RightDoubleBracket]-
              base)*(data\[LeftDoubleBracket]i,1\[RightDoubleBracket]-
              data\[LeftDoubleBracket]i-1,1\[RightDoubleBracket])];
    width=Abs[tot/amp];
    fitResult=
      NonlinearRegress[data,gaussian[baseFit,ampFit,centroidFit,widthFit,x],
        x,{{baseFit,base},{ampFit,amp},{centroidFit,
            centre\[LeftDoubleBracket]1\[RightDoubleBracket]},{widthFit,
            width}},RegressionReport\[Rule]{BestFitParameters,ParameterTable},
        MaxIterations\[Rule]150];
    fitGraph=
      Show[{Plot[
            gaussian[baseFit,ampFit,centroidFit,widthFit,
                x]/.(BestFitParameters/.fitResult),{x,First[First[data]],
              First[Last[data]]},PlotStyle\[Rule]Red,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity],
          ListPlot[data,PlotJoined\[Rule]False,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity]},
        DisplayFunction\[Rule]$DisplayFunction];
    getFitResult[] = fitResult;
    getFitGraph[] = fitGraph;
    getGuesses[]={base,amp,centre,width};
    getBase[]=baseFit/.(BestFitParameters/.fitResult);
    getAmplitude[]=ampFit/.(BestFitParameters/.fitResult);
    getCentroid[]=centroidFit/.(BestFitParameters/.fitResult);
    getWidth[]=widthFit/.(BestFitParameters/.fitResult);)

lorentzFitManual[data_,offsetGuess_,ampGuess_,centroidGuess_,widthGuess_]:=(
    fitResult=
      NonlinearRegress[data,lorentz[baseFit,ampFit,centroidFit,widthFit,x],
        x,{{baseFit,offsetGuess},{ampFit,ampGuess},{centroidFit,
            centroidGuess},{widthFit,widthGuess}},
        RegressionReport\[Rule]{BestFitParameters,ParameterTable},
        MaxIterations\[Rule]150];
    fitGraph=
      Show[{Plot[
            lorentz[baseFit,ampFit,centroidFit,widthFit,
                x]/.(BestFitParameters/.fitResult),{x,First[First[data]],
              First[Last[data]]},PlotStyle\[Rule]Red,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity],
          ListPlot[data,PlotJoined\[Rule]False,PlotRange\[Rule]All,
            DisplayFunction\[Rule]Identity]},
        DisplayFunction\[Rule]$DisplayFunction];
    getFitResult[]=fitResult;
    getFitGraph[]=fitGraph;
    getGuesses[]={offsetGuess,ampGuess,centroidGuess,widthGuess};)

End[]

EndPackage[]