(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["SEDM3`Statistics`"];


bootstrapReplicate::usage="";
trimmedMeanAndBSErr::usage="";
diffWithError::usage="";
sumWithError::usage="";
productWithError::usage="";
quotientWithError::usage="";


Begin["`Private`"];

bootstrapReplicate[dataset_]:=Module[{l,rnds},l=Length[dataset];rnds=Table[RandomInteger[l-1]+1,{l}];dataset[[rnds]]];

trimmedMeanAndBSErr[dat_,trimLevel_:0.05,replicates_:1000]:={Mean[#],StandardDeviation[#]}&[Table[TrimmedMean[bootstrapReplicate[dat],trimLevel],{replicates}]]
trimmedMeanAndBSErr[{}]:={0,0}

diffWithError={(#[[1]][[1]]-#[[2]][[1]]),Sqrt[#[[1]][[2]]^2+#[[2]][[2]]^2]}&;
sumWithError={(#[[1]][[1]]+#[[2]][[1]]),Sqrt[#[[1]][[2]]^2+#[[2]][[2]]^2]}&;

productWithError={#[[1]][[1]]#[[2]][[1]],Sqrt[#[[2]][[1]]^2 #[[1]][[2]]^2+#[[1]][[1]]^2 #[[2]][[2]]^2]}&;

quotientWithError={#[[1]][[1]]/#[[2]][[1]],#[[1]][[1]]/#[[2]][[1]] Sqrt[#[[1]][[2]]^2/#[[1]][[1]]^2+#[[2]][[2]]^2/#[[2]][[1]]^2]}&;



End[];
EndPackage[];
