<?xml version="1.0" encoding="utf-8"?><Database Name="EDMDatabase" Class="BlockDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=EDMDatabase;Integrated Security=True" SettingsObjectName="SonOfSirCachealot.Properties.Settings" SettingsPropertyName="EDMDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DBBlocks" Member="DBBlocks">
    <Type Name="DBBlock">
      <Column Name="blockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cluster" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="clusterIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="include" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="eState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="bState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="rfState" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ePlus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="eMinus" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="blockTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="configBytes" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DBBlock_DBTOFChannelSet" Member="DBTOFChannelSets" ThisKey="blockID" OtherKey="blockID" Type="DBTOFChannelSet" />
      <Association Name="DBBlock_DBDBlock" Member="DBDBlocks" ThisKey="blockID" OtherKey="blockID" Type="DBDBlock" />
    </Type>
  </Table>
  <Table Name="dbo.DBTOFChannelSets" Member="DBTOFChannelSets">
    <Type Name="DBTOFChannelSet">
      <Column Name="tcsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="blockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="detector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="tcsData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DBBlock_DBTOFChannelSet" Member="DBBlock" ThisKey="blockID" OtherKey="blockID" Type="DBBlock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DBDBlocks" Member="DBDBlocks">
    <Type Name="DBDBlock">
      <Column Name="dblockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="blockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="aTag" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="dblockData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DBBlock_DBDBlock" Member="DBBlock" ThisKey="blockID" OtherKey="blockID" Type="DBBlock" IsForeignKey="true" />
    </Type>
  </Table>
</Database>